-- ROLLBACK PREVIEW ONLY. DO NOT EXECUTE WITHOUT EXPLICIT APPROVAL.
BEGIN;

DO $rollback$
DECLARE
  difference_count integer;
  deleted_count integer;
BEGIN
  IF to_regclass('public.restaurant_weekly_hours') IS NULL
    OR (SELECT count(*) FROM public.restaurant_weekly_hours) <> 112 THEN
    RAISE EXCEPTION 'Initial weekly rollback stopped: table or row-count baseline changed';
  END IF;

  WITH expected_rows (restaurant_id, iso_weekday, day_status, open_time, close_time, closes_next_day, break_status, break_start, break_end, note, source, last_verified_at) AS (
  VALUES
    ('C001'::text, 1::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 2::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 3::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 4::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 5::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 6::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 1::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 2::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 3::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 4::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 5::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 6::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 1::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 2::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 3::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 4::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 5::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 6::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 1::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 2::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 3::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 4::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 5::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 1::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 2::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 3::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 4::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 5::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 6::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 1::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 2::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 3::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 4::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 5::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 7::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 6::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 1::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 2::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 3::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 4::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 5::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 6::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 7::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 1::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 2::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 3::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 4::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 5::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 6::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz)
),
  actual_rows AS (
    SELECT restaurant_id, iso_weekday, day_status, open_time, close_time, closes_next_day, break_status, break_start, break_end, note, source, last_verified_at
    FROM public.restaurant_weekly_hours
  ),
  differences AS (
    (SELECT * FROM expected_rows EXCEPT SELECT * FROM actual_rows)
    UNION ALL
    (SELECT * FROM actual_rows EXCEPT SELECT * FROM expected_rows)
  )
  SELECT count(*) INTO difference_count FROM differences;

  IF difference_count <> 0 THEN
    RAISE EXCEPTION 'Initial weekly rollback stopped: exact migration rows changed';
  END IF;

  WITH expected_rows (restaurant_id, iso_weekday, day_status, open_time, close_time, closes_next_day, break_status, break_start, break_end, note, source, last_verified_at) AS (
  VALUES
    ('C001'::text, 1::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 2::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 3::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 4::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 5::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 6::smallint, 'open'::text, '10:00:00'::time without time zone, '20:40:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C001'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 1::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 2::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 3::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 4::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 5::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 6::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C002'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C003'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 1::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 2::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 3::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 4::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 5::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 6::smallint, 'open'::text, '10:20:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C007'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C009'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 1::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 2::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 3::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 4::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 5::smallint, 'open'::text, '10:30:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'scheduled'::text, '14:30:00'::time without time zone, '17:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C010'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C011'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 1::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 2::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 3::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 4::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 5::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 6::smallint, 'open'::text, '10:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C013'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '14:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C014'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 1::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 2::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 3::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 4::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 5::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C015'::text, 7::smallint, 'open'::text, '09:40:00'::time without time zone, '20:30:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 6::smallint, 'open'::text, '11:00:00'::time without time zone, '21:10:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C017'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 1::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 2::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 3::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 4::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 5::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 6::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C019'::text, 7::smallint, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 1::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 2::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 3::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 4::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 5::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 6::smallint, 'open'::text, '09:00:00'::time without time zone, '20:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C020'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C022'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 1::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 2::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 3::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 4::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 5::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 6::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C023'::text, 7::smallint, 'open'::text, '11:00:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'unknown'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 1::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 2::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 3::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 4::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 5::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 6::smallint, 'open'::text, '10:30:00'::time without time zone, '21:00:00'::time without time zone, false::boolean, 'scheduled'::text, '15:00:00'::time without time zone, '16:00:00'::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz),
    ('C027'::text, 7::smallint, 'closed'::text, NULL::time without time zone, NULL::time without time zone, false::boolean, 'none'::text, NULL::time without time zone, NULL::time without time zone, NULL::text, 'legacy_migration'::text, NULL::timestamptz)
)
  DELETE FROM public.restaurant_weekly_hours AS actual
  USING expected_rows AS expected
  WHERE actual.restaurant_id IS NOT DISTINCT FROM expected.restaurant_id
      AND actual.iso_weekday IS NOT DISTINCT FROM expected.iso_weekday
      AND actual.day_status IS NOT DISTINCT FROM expected.day_status
      AND actual.open_time IS NOT DISTINCT FROM expected.open_time
      AND actual.close_time IS NOT DISTINCT FROM expected.close_time
      AND actual.closes_next_day IS NOT DISTINCT FROM expected.closes_next_day
      AND actual.break_status IS NOT DISTINCT FROM expected.break_status
      AND actual.break_start IS NOT DISTINCT FROM expected.break_start
      AND actual.break_end IS NOT DISTINCT FROM expected.break_end
      AND actual.note IS NOT DISTINCT FROM expected.note
      AND actual.source IS NOT DISTINCT FROM expected.source
      AND actual.last_verified_at IS NOT DISTINCT FROM expected.last_verified_at;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  IF deleted_count <> 112 OR (SELECT count(*) FROM public.restaurant_weekly_hours) <> 0 THEN
    RAISE EXCEPTION 'Initial weekly rollback stopped: expected exactly 112 deletions, got %', deleted_count;
  END IF;
END;
$rollback$;

-- This preview always rolls back. A separately approved rollback package is required.
ROLLBACK;
