window.CHANGWON_FOOD_DATA = {
  "restaurants": [
    {
      "id": "C001",
      "name": "리코리코",
      "area": "정문",
      "address": "경상남도 창원시 의창구 퇴촌로25번길 6-32",
      "lat": 35.2425,
      "lng": 128.6898,
      "phone": "055-267-4300",
      "openTime": "10:00:00",
      "closeTime": "20:40:00",
      "breakTime": "",
      "closedDays": "일요일",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 54,
      "reviewCount": 173,
      "source": "네이버지도",
      "lastChecked": "2026-06-16T00:00:00",
      "memo": ""
    },
    {
      "id": "C002",
      "name": "달인의찜닭",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 43",
      "lat": 35.2423,
      "lng": 128.6898,
      "phone": "055-285-3070",
      "openTime": "10:30:00",
      "closeTime": "21:00:00",
      "breakTime": "",
      "closedDays": "일요일",
      "takeout": false,
      "delivery": false,
      "alone": false,
      "group": true,
      "seats": 70,
      "reviewCount": 146,
      "source": "네이버지도",
      "lastChecked": "2026-06-16T00:00:00",
      "memo": ""
    },
    {
      "id": "C003",
      "name": "엄마손",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 39",
      "lat": 35.2422,
      "lng": 128.6895,
      "phone": "X",
      "openTime": "X",
      "closeTime": "X",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 35,
      "reviewCount": 176,
      "source": "네이버지도",
      "lastChecked": "2026-06-16T00:00:00",
      "memo": ""
    },
    {
      "id": "C004",
      "name": "한솥도시락",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 37",
      "lat": 35.2421,
      "lng": 128.6893,
      "phone": "055-980-5519",
      "openTime": "08:15:00",
      "closeTime": "20:30:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 15,
      "reviewCount": 561,
      "source": "네이버지도",
      "lastChecked": "2026-06-16T00:00:00",
      "memo": ""
    },
    {
      "id": "C005",
      "name": "경대컵밥",
      "area": "정문",
      "address": "경남 창원시 의창구 사림동 53-6",
      "lat": 35.2422,
      "lng": 128.689,
      "phone": "055-275-3353",
      "openTime": "10:00:00",
      "closeTime": "19:30:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 25,
      "reviewCount": 37,
      "source": "기타",
      "lastChecked": "2026-06-16T00:00:00",
      "memo": ""
    },
    {
      "id": "C006",
      "name": "쇼부라멘",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 6-20 1층",
      "lat": 35.2422,
      "lng": 128.689,
      "phone": "055-267-0604",
      "openTime": "09:00:00",
      "closeTime": "16:00:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 12,
      "reviewCount": 6,
      "source": "카카오맵",
      "lastChecked": "2026-06-16T00:00:00",
      "memo": ""
    },
    {
      "id": "C007",
      "name": "봉구스 밥버거",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 37",
      "lat": 35.2421,
      "lng": 128.6893,
      "phone": "055-281-9631",
      "openTime": "10:20:00",
      "closeTime": "20:00:00",
      "breakTime": "X",
      "closedDays": "일요일",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 8,
      "reviewCount": 94,
      "source": "네이버지도",
      "lastChecked": "2026-06-17T00:00:00",
      "memo": ""
    },
    {
      "id": "C008",
      "name": "미스사이공",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 6-24 1층",
      "lat": 35.2423,
      "lng": 128.6893,
      "phone": "055-262-5590",
      "openTime": "09:00:00",
      "closeTime": "19:00:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 516,
      "source": "네이버지도",
      "lastChecked": "2026-06-18T00:00:00",
      "memo": ""
    },
    {
      "id": "C009",
      "name": "맘스터치",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 6-21",
      "lat": 35.2425,
      "lng": 128.6891,
      "phone": "055-286-3231",
      "openTime": "X",
      "closeTime": "X",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 30,
      "reviewCount": 524,
      "source": "네이버지도",
      "lastChecked": "2026-06-19T00:00:00",
      "memo": ""
    },
    {
      "id": "C010",
      "name": "따뜻한밥상",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 6-15 따뜻한밥상",
      "lat": 35.2425,
      "lng": 128.6888,
      "phone": "X",
      "openTime": "10:30:00",
      "closeTime": "20:00:00",
      "breakTime": "14:30-17:00",
      "closedDays": "토요일,일요일",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 30,
      "reviewCount": 107,
      "source": "네이버지도",
      "lastChecked": "2026-06-20T00:00:00",
      "memo": ""
    },
    {
      "id": "C011",
      "name": "소소소국수집",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 6-5",
      "lat": 35.2422,
      "lng": 128.6883,
      "phone": "055-261-5233",
      "openTime": "X",
      "closeTime": "X",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 40,
      "reviewCount": 65,
      "source": "네이버지도",
      "lastChecked": "2026-06-21T00:00:00",
      "memo": ""
    },
    {
      "id": "C012",
      "name": "김밥천국",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 2",
      "lat": 35.2422,
      "lng": 128.6883,
      "phone": "055-274-2588",
      "openTime": "08:00:00",
      "closeTime": "22:00:00",
      "breakTime": "15:00-17:00",
      "closedDays": "X",
      "takeout": true,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 110,
      "source": "네이버지도",
      "lastChecked": "2026-06-22T00:00:00",
      "memo": ""
    },
    {
      "id": "C013",
      "name": "쌈마이 닭쌈밥",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로9번길 6-20 101호",
      "lat": 35.2419,
      "lng": 128.6876,
      "phone": "0507-1316-9003",
      "openTime": "10:00:00",
      "closeTime": "20:00:00",
      "breakTime": "X",
      "closedDays": "일요일",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 244,
      "source": "네이버지도",
      "lastChecked": "2026-06-23T00:00:00",
      "memo": ""
    },
    {
      "id": "C014",
      "name": "창대 비빔밥 뷔페",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 19 지하",
      "lat": 35.2418,
      "lng": 128.6875,
      "phone": "0507-1327-9883",
      "openTime": "11:00:00",
      "closeTime": "14:00:00",
      "breakTime": "X",
      "closedDays": "토요일,일요일",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 40,
      "reviewCount": 85,
      "source": "네이버지도",
      "lastChecked": "2026-06-24T00:00:00",
      "memo": ""
    },
    {
      "id": "C015",
      "name": "알촌",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 27 1층",
      "lat": 35.2418,
      "lng": 128.6883,
      "phone": "055-282-6363",
      "openTime": "09:40:00",
      "closeTime": "20:30:00",
      "breakTime": "X",
      "closedDays": "토요일",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 427,
      "source": "네이버지도",
      "lastChecked": "2026-06-25T00:00:00",
      "memo": ""
    },
    {
      "id": "C016",
      "name": "롯데리아",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 31-1",
      "lat": 35.242,
      "lng": 128.6887,
      "phone": "X",
      "openTime": "10:00:00",
      "closeTime": "20:00:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 35,
      "reviewCount": 1200,
      "source": "네이버지도",
      "lastChecked": "2026-06-26T00:00:00",
      "memo": ""
    },
    {
      "id": "C017",
      "name": "이삭토스트",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로 327",
      "lat": 35.2416,
      "lng": 128.6907,
      "phone": "055-261-1676",
      "openTime": "11:00:00",
      "closeTime": "21:10:00",
      "breakTime": "X",
      "closedDays": "일요일",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 10,
      "reviewCount": 310,
      "source": "네이버지도",
      "lastChecked": "2026-06-27T00:00:00",
      "memo": ""
    },
    {
      "id": "C018",
      "name": "뼈따구",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로 327",
      "lat": 35.2416,
      "lng": 128.6907,
      "phone": "X",
      "openTime": "10:00:00",
      "closeTime": "21:00:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 50,
      "reviewCount": 0,
      "source": "지인 제보",
      "lastChecked": "2026-06-28T00:00:00",
      "memo": ""
    },
    {
      "id": "C019",
      "name": "밀밭이야기",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로 323",
      "lat": 35.2414,
      "lng": 128.6908,
      "phone": "055-267-5670",
      "openTime": "X",
      "closeTime": "X",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 30,
      "reviewCount": 0,
      "source": "지인 제보",
      "lastChecked": "2026-06-29T00:00:00",
      "memo": ""
    },
    {
      "id": "C020",
      "name": "김밥일번지",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로 319-2 지하1층",
      "lat": 35.2412,
      "lng": 128.6907,
      "phone": "055-263-7772",
      "openTime": "09:00:00",
      "closeTime": "20:00:00",
      "breakTime": "X",
      "closedDays": "일요일",
      "takeout": true,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 50,
      "reviewCount": 874,
      "source": "네이버지도",
      "lastChecked": "2026-06-30T00:00:00",
      "memo": ""
    },
    {
      "id": "C021",
      "name": "팔팔마라탕",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로 41 1층",
      "lat": 35.2422,
      "lng": 128.6897,
      "phone": "055-261-6680",
      "openTime": "10:50:00",
      "closeTime": "21:30:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 299,
      "source": "네이버지도",
      "lastChecked": "2026-07-01T00:00:00",
      "memo": ""
    },
    {
      "id": "C022",
      "name": "차곡히",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 7 1층",
      "lat": 35.2424,
      "lng": 128.6878,
      "phone": "0507-1345-5163",
      "openTime": "11:00:00",
      "closeTime": "21:00:00",
      "breakTime": "X",
      "closedDays": "토요일,일요일",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 284,
      "source": "네이버지도",
      "lastChecked": "2026-07-02T00:00:00",
      "memo": ""
    },
    {
      "id": "C023",
      "name": "레빗테이블",
      "area": "정문",
      "address": "경남 창원시 의창구 퇴촌로25번길 7 1층 래빗테이블",
      "lat": 35.2424,
      "lng": 128.6877,
      "phone": "0507-1308-0531",
      "openTime": "11:00:00",
      "closeTime": "21:00:00",
      "breakTime": "X",
      "closedDays": "토요일",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 25,
      "reviewCount": 168,
      "source": "네이버지도",
      "lastChecked": "2026-07-03T00:00:00",
      "memo": ""
    },
    {
      "id": "C024",
      "name": "고가밀면",
      "area": "정문",
      "address": "경남 창원시 의창구 사림로137번길 1",
      "lat": 35.2431,
      "lng": 128.6857,
      "phone": "X",
      "openTime": "10:50:00",
      "closeTime": "15:30:00",
      "breakTime": "X",
      "closedDays": "2,4번째 일요일",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 40,
      "reviewCount": 240,
      "source": "네이버지도",
      "lastChecked": "2026-07-04T00:00:00",
      "memo": ""
    },
    {
      "id": "C025",
      "name": "가야밀면",
      "area": "정문",
      "address": "경남 창원시 의창구 창이대로483번길 29-24",
      "lat": 35.2412,
      "lng": 128.6887,
      "phone": "055-262-2008",
      "openTime": "11:00:00",
      "closeTime": "19:00:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 20,
      "reviewCount": 18,
      "source": "네이버지도",
      "lastChecked": "2026-07-05T00:00:00",
      "memo": ""
    },
    {
      "id": "C026",
      "name": "유가네 닭갈비",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로293번길 28 우영프라자 1층 115호",
      "lat": 35.2409,
      "lng": 128.6881,
      "phone": "055-273-8250",
      "openTime": "11:00:00",
      "closeTime": "22:00:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 40,
      "reviewCount": 610,
      "source": "네이버지도",
      "lastChecked": "2026-07-06T00:00:00",
      "memo": ""
    },
    {
      "id": "C027",
      "name": "호호돼지국밥",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로 281",
      "lat": 35.2383,
      "lng": 128.6891,
      "phone": "055-263-3889",
      "openTime": "10:30:00",
      "closeTime": "21:00:00",
      "breakTime": "15:00-16:00",
      "closedDays": "일요일",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 60,
      "reviewCount": 603,
      "source": "네이버지도",
      "lastChecked": "2026-07-07T00:00:00",
      "memo": ""
    },
    {
      "id": "C028",
      "name": "장독짜장",
      "area": "정문",
      "address": "경남 창원시 의창구 창이대로469번길 19",
      "lat": 35.2404,
      "lng": 128.6878,
      "phone": "055-288-1536",
      "openTime": "10:30:00",
      "closeTime": "20:20:00",
      "breakTime": "X",
      "closedDays": "X",
      "takeout": true,
      "delivery": true,
      "alone": true,
      "group": true,
      "seats": 80,
      "reviewCount": 503,
      "source": "네이버지도",
      "lastChecked": "2026-07-08T00:00:00",
      "memo": ""
    },
    {
      "id": "C029",
      "name": "돌솥밥수",
      "area": "정문",
      "address": "경남 창원시 의창구 용지로293번길 21 반지하층 돌솥밥수",
      "lat": 35.2403,
      "lng": 128.688,
      "phone": "055-261-2905",
      "openTime": "11:00:00",
      "closeTime": "20:30:00",
      "breakTime": "15:00-17:00",
      "closedDays": "X",
      "takeout": false,
      "delivery": false,
      "alone": true,
      "group": true,
      "seats": 80,
      "reviewCount": 293,
      "source": "네이버지도",
      "lastChecked": "2026-07-09T00:00:00",
      "memo": ""
    }
  ],
  "menus": [
    {
      "id": "M001",
      "restaurantId": "C001",
      "restaurantName": "리코리코",
      "name": "닭고기 부리또",
      "category": "햄버거",
      "price": 5000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "빠른식사",
        "든든함",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M002",
      "restaurantId": "C001",
      "restaurantName": "리코리코",
      "name": "소고기 부리또",
      "category": "햄버거",
      "price": 5800,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "빠른식사",
        "든든함",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M003",
      "restaurantId": "C001",
      "restaurantName": "리코리코",
      "name": "섞어 부리또",
      "category": "햄버거",
      "price": 5000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "빠른식사",
        "든든함",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M004",
      "restaurantId": "C001",
      "restaurantName": "리코리코",
      "name": "치킨텐더 부리또",
      "category": "햄버거",
      "price": 6500,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "빠른식사",
        "든든함",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M005",
      "restaurantId": "C001",
      "restaurantName": "리코리코",
      "name": "제육 부리또",
      "category": "햄버거",
      "price": 6000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "빠른식사",
        "든든함",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M006",
      "restaurantId": "C002",
      "restaurantName": "달인의 찜닭",
      "name": "달인 순살 찜닭",
      "category": "찜/탕",
      "price": 23000,
      "spicy": 3,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "단체",
        "데이트",
        "든든함",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M007",
      "restaurantId": "C002",
      "restaurantName": "달인의 찜닭",
      "name": "달인 치즈순살 찜닭",
      "category": "찜/탕",
      "price": 26000,
      "spicy": 3,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "단체",
        "데이트",
        "든든함",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M008",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "두루치기",
      "category": "한식",
      "price": 11000,
      "spicy": 2,
      "salty": 2,
      "sweet": 4,
      "portion": 3,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M009",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "된장찌개",
      "category": "한식",
      "price": 6000,
      "spicy": 1,
      "salty": 3,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M010",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "김치찌개",
      "category": "한식",
      "price": 6000,
      "spicy": 1,
      "salty": 3,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M011",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "순두부찌개",
      "category": "한식",
      "price": 6500,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M012",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "뚝배기불고기",
      "category": "한식",
      "price": 8000,
      "spicy": 0,
      "salty": 2,
      "sweet": 4,
      "portion": 4,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M013",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "돌솥비빔밥",
      "category": "한식",
      "price": 6500,
      "spicy": 0,
      "salty": 2,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M014",
      "restaurantId": "C003",
      "restaurantName": "엄마손",
      "name": "육개장",
      "category": "한식",
      "price": 7000,
      "spicy": 3,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "해장"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M015",
      "restaurantId": "C004",
      "restaurantName": "한솥도시락",
      "name": "빅치킨마요",
      "category": "도시락",
      "price": 4600,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M016",
      "restaurantId": "C004",
      "restaurantName": "한솥도시락",
      "name": "제육 많이 덮밥",
      "category": "도시락",
      "price": 6500,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M017",
      "restaurantId": "C004",
      "restaurantName": "한솥도시락",
      "name": "돈까스 도련님 고기고기",
      "category": "도시락",
      "price": 7300,
      "spicy": 0,
      "salty": 2,
      "sweet": 2,
      "portion": 5,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M018",
      "restaurantId": "C004",
      "restaurantName": "한솥도시락",
      "name": "왕카레돈까스 덮밥",
      "category": "도시락",
      "price": 6700,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M019",
      "restaurantId": "C005",
      "restaurantName": "경대컵밥",
      "name": "경대컵밥도시락",
      "category": "도시락",
      "price": 6400,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M020",
      "restaurantId": "C005",
      "restaurantName": "경대컵밥",
      "name": "오리훈제컵밥도시락",
      "category": "도시락",
      "price": 7400,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M021",
      "restaurantId": "C005",
      "restaurantName": "경대컵밥",
      "name": "제육컵밥도시락",
      "category": "도시락",
      "price": 7400,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M022",
      "restaurantId": "C005",
      "restaurantName": "경대컵밥",
      "name": "치즈컵밥도시락",
      "category": "도시락",
      "price": 7400,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "가성비",
        "혼밥",
        "단체",
        "든든함",
        "가볍게",
        "포장",
        "배달",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M023",
      "restaurantId": "C006",
      "restaurantName": "쇼부라멘",
      "name": "소유라멘",
      "category": "일식/돈까스",
      "price": 5500,
      "spicy": 0,
      "salty": 4,
      "sweet": 4,
      "portion": 2,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "가볍게",
        "시험기간",
        "빠른식사",
        "해장",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M024",
      "restaurantId": "C006",
      "restaurantName": "쇼부라멘",
      "name": "미소라멘",
      "category": "일식/돈까스",
      "price": 6000,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 2,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "가볍게",
        "시험기간",
        "빠른식사",
        "해장",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M025",
      "restaurantId": "C006",
      "restaurantName": "쇼부라멘",
      "name": "돈코츠라멘",
      "category": "일식/돈까스",
      "price": 6500,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 2,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "가볍게",
        "시험기간",
        "빠른식사",
        "해장",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M026",
      "restaurantId": "C006",
      "restaurantName": "쇼부라멘",
      "name": "탄탄멘",
      "category": "일식/돈까스",
      "price": 7000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "가볍게",
        "시험기간",
        "빠른식사",
        "해장",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M027",
      "restaurantId": "C007",
      "restaurantName": "봉구스밥버거",
      "name": "봉구스",
      "category": "도시락",
      "price": 3500,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 1,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "포장",
        "배달",
        "가성비"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M028",
      "restaurantId": "C007",
      "restaurantName": "봉구스밥버거",
      "name": "햄치즈",
      "category": "도시락",
      "price": 5100,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 2,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M029",
      "restaurantId": "C007",
      "restaurantName": "봉구스밥버거",
      "name": "봉구킹",
      "category": "도시락",
      "price": 7300,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M030",
      "restaurantId": "C007",
      "restaurantName": "봉구스밥버거",
      "name": "봉구퀸",
      "category": "도시락",
      "price": 7300,
      "spicy": 0,
      "salty": 3,
      "sweet": 4,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M031",
      "restaurantId": "C008",
      "restaurantName": "미스사이공",
      "name": "소고기 쌀국수",
      "category": "아시안",
      "price": 6500,
      "spicy": 0,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M032",
      "restaurantId": "C008",
      "restaurantName": "미스사이공",
      "name": "닭고기 쌀국수",
      "category": "아시안",
      "price": 6500,
      "spicy": 0,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M033",
      "restaurantId": "C008",
      "restaurantName": "미스사이공",
      "name": "사이공 볶음밥",
      "category": "아시안",
      "price": 6500,
      "spicy": 0,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "데이트"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M034",
      "restaurantId": "C009",
      "restaurantName": "맘스터치",
      "name": "싸이버거 세트",
      "category": "햄버거",
      "price": 9000,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 5,
      "value": 2,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "포장",
        "배달",
        "단체",
        "든든함"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M035",
      "restaurantId": "C009",
      "restaurantName": "맘스터치",
      "name": "아라비아따치즈버거 세트",
      "category": "햄버거",
      "price": 11500,
      "spicy": 2,
      "salty": 3,
      "sweet": 4,
      "portion": 5,
      "value": 2,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "포장",
        "배달",
        "단체",
        "든든함"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M036",
      "restaurantId": "C009",
      "restaurantName": "맘스터치",
      "name": "화이트갈릭싸이버거 세트",
      "category": "햄버거",
      "price": 9600,
      "spicy": 1,
      "salty": 3,
      "sweet": 4,
      "portion": 5,
      "value": 2,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "포장",
        "배달",
        "단체",
        "든든함"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M037",
      "restaurantId": "C010",
      "restaurantName": "따뜻한밥상",
      "name": "김치찌개",
      "category": "한식",
      "price": 5000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "시험기간",
        "빠른식사",
        "든든함",
        "가성비",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M038",
      "restaurantId": "C011",
      "restaurantName": "소소소국수집",
      "name": "잔치국수",
      "category": "분식",
      "price": 6000,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "시험기간",
        "든든함",
        "빠른식사",
        "해장",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M039",
      "restaurantId": "C011",
      "restaurantName": "소소소국수집",
      "name": "비빔국수",
      "category": "분식",
      "price": 7000,
      "spicy": 2,
      "salty": 3,
      "sweet": 4,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "시험기간",
        "든든함",
        "빠른식사",
        "해장",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M040",
      "restaurantId": "C011",
      "restaurantName": "소소소국수집",
      "name": "열무국수",
      "category": "분식",
      "price": 7000,
      "spicy": 2,
      "salty": 3,
      "sweet": 4,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "시험기간",
        "든든함",
        "빠른식사",
        "해장",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M041",
      "restaurantId": "C012",
      "restaurantName": "김밥천국",
      "name": "참치마요김밥",
      "category": "분식",
      "price": 3500,
      "spicy": 0,
      "salty": 2,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 5,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "가성비",
        "포장"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M042",
      "restaurantId": "C012",
      "restaurantName": "김밥천국",
      "name": "순두부찌개",
      "category": "분식",
      "price": 5500,
      "spicy": 3,
      "salty": 3,
      "sweet": 2,
      "portion": 1,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "해장"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M043",
      "restaurantId": "C012",
      "restaurantName": "김밥천국",
      "name": "돈까스",
      "category": "분식",
      "price": 6000,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M044",
      "restaurantId": "C013",
      "restaurantName": "쌈마이 닭쌈밥",
      "name": "쌈마이 닭쌈밥 백반도시락",
      "category": "도시락",
      "price": 8900,
      "spicy": 0,
      "salty": 3,
      "sweet": 0,
      "portion": 5,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "시험기간",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M045",
      "restaurantId": "C013",
      "restaurantName": "쌈마이 닭쌈밥",
      "name": "양념닭쌈밥 백반도시락",
      "category": "도시락",
      "price": 9500,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 5,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "시험기간",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M046",
      "restaurantId": "C014",
      "restaurantName": "창대 비빔밥 뷔페",
      "name": "비빔밥",
      "category": "한식",
      "price": 8000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 3,
      "speed": 5,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M047",
      "restaurantId": "C015",
      "restaurantName": "알촌",
      "name": "순한알밥",
      "category": "한식",
      "price": 5300,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "포장",
        "배달",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M048",
      "restaurantId": "C015",
      "restaurantName": "알촌",
      "name": "약매알밥",
      "category": "한식",
      "price": 5500,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "포장",
        "배달",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M049",
      "restaurantId": "C015",
      "restaurantName": "알촌",
      "name": "매콤알밥",
      "category": "한식",
      "price": 5600,
      "spicy": 4,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "든든함",
        "빠른식사",
        "포장",
        "배달",
        "가볍게"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M050",
      "restaurantId": "C016",
      "restaurantName": "롯데리아",
      "name": "모짜렐라 인 더 버거 베이컨 세트",
      "category": "햄버거",
      "price": 11700,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 2,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "단체",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M051",
      "restaurantId": "C016",
      "restaurantName": "롯데리아",
      "name": "불고기버거",
      "category": "햄버거",
      "price": 8900,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 2,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "단체",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M052",
      "restaurantId": "C016",
      "restaurantName": "롯데리아",
      "name": "핫크리스피치킨버거 세트",
      "category": "햄버거",
      "price": 10000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 2,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "단체",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M053",
      "restaurantId": "C017",
      "restaurantName": "이삭토스트",
      "name": "햄스페셜 토스트",
      "category": "햄버거",
      "price": 5100,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "단체",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M054",
      "restaurantId": "C017",
      "restaurantName": "이삭토스트",
      "name": "햄치즈 토스트",
      "category": "햄버거",
      "price": 4500,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "단체",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M055",
      "restaurantId": "C017",
      "restaurantName": "이삭토스트",
      "name": "베이컨 포테이토 피자",
      "category": "햄버거",
      "price": 6500,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 3,
      "value": 3,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "시험기간",
        "단체",
        "빠른식사",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M056",
      "restaurantId": "C018",
      "restaurantName": "뼈따구",
      "name": "뼈해장국",
      "category": "찜/탕",
      "price": 10000,
      "spicy": 1,
      "salty": 3,
      "sweet": 2,
      "portion": 4,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "시험기간",
        "포장",
        "해장",
        "비오는날",
        "든든함"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M057",
      "restaurantId": "C018",
      "restaurantName": "뼈따구",
      "name": "콩나물해장국",
      "category": "찜/탕",
      "price": 10000,
      "spicy": 1,
      "salty": 3,
      "sweet": 2,
      "portion": 2,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "시험기간",
        "포장",
        "해장",
        "비오는날",
        "든든함"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M058",
      "restaurantId": "C019",
      "restaurantName": "밀밭이야기",
      "name": "촌국수",
      "category": "한식",
      "price": 6000,
      "spicy": 1,
      "salty": 3,
      "sweet": 1,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M059",
      "restaurantId": "C019",
      "restaurantName": "밀밭이야기",
      "name": "비빔국수",
      "category": "한식",
      "price": 7000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M060",
      "restaurantId": "C019",
      "restaurantName": "밀밭이야기",
      "name": "양푼비빔밥",
      "category": "한식",
      "price": 8000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M061",
      "restaurantId": "C019",
      "restaurantName": "밀밭이야기",
      "name": "해물전",
      "category": "한식",
      "price": 7000,
      "spicy": 1,
      "salty": 2,
      "sweet": 0,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M062",
      "restaurantId": "C019",
      "restaurantName": "밀밭이야기",
      "name": "수제비",
      "category": "한식",
      "price": 7000,
      "spicy": 0,
      "salty": 3,
      "sweet": 1,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M063",
      "restaurantId": "C019",
      "restaurantName": "밀밭이야기",
      "name": "들깨칼국수",
      "category": "한식",
      "price": 9000,
      "spicy": 0,
      "salty": 3,
      "sweet": 2,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M064",
      "restaurantId": "C020",
      "restaurantName": "김밥일번지",
      "name": "일번지김밥",
      "category": "분식",
      "price": 4000,
      "spicy": 0,
      "salty": 2,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날",
        "포장",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M065",
      "restaurantId": "C020",
      "restaurantName": "김밥일번지",
      "name": "콩나물비빔밥",
      "category": "분식",
      "price": 7000,
      "spicy": 1,
      "salty": 2,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날",
        "포장",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M066",
      "restaurantId": "C020",
      "restaurantName": "김밥일번지",
      "name": "일번지라면",
      "category": "분식",
      "price": 4500,
      "spicy": 2,
      "salty": 3,
      "sweet": 1,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날",
        "포장",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M067",
      "restaurantId": "C020",
      "restaurantName": "김밥일번지",
      "name": "엄마떡볶이",
      "category": "분식",
      "price": 7000,
      "spicy": 3,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "비오는날",
        "포장",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M068",
      "restaurantId": "C021",
      "restaurantName": "팔팔마라탕",
      "name": "88마라탕",
      "category": "찜/탕",
      "price": 9800,
      "spicy": 5,
      "salty": 3,
      "sweet": 1,
      "portion": 3,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "포장",
        "배달",
        "스트레스"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M069",
      "restaurantId": "C022",
      "restaurantName": "차곡히",
      "name": "순두부 제육볶음세트",
      "category": "한식",
      "price": 12000,
      "spicy": 3,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 2,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "단체",
        "데이트",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M070",
      "restaurantId": "C022",
      "restaurantName": "차곡히",
      "name": "된장찌개 제육볶음 세트",
      "category": "한식",
      "price": 12000,
      "spicy": 3,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 2,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "든든함",
        "단체",
        "데이트",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M071",
      "restaurantId": "C023",
      "restaurantName": "레빗테이블",
      "name": "수제등심 돈가스",
      "category": "양식",
      "price": 10000,
      "spicy": 0,
      "salty": 2,
      "sweet": 1,
      "portion": 5,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "든든함",
        "데이트",
        "스트레스"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M072",
      "restaurantId": "C023",
      "restaurantName": "레빗테이블",
      "name": "레빗크림 파스타",
      "category": "양식",
      "price": 9500,
      "spicy": 1,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "든든함",
        "데이트",
        "스트레스"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M073",
      "restaurantId": "C023",
      "restaurantName": "레빗테이블",
      "name": "레빗로제 파스타",
      "category": "양식",
      "price": 11000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "든든함",
        "데이트",
        "스트레스"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M074",
      "restaurantId": "C023",
      "restaurantName": "레빗테이블",
      "name": "베이컨 크림 리조또",
      "category": "양식",
      "price": 11000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 2,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "든든함",
        "데이트",
        "스트레스"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M075",
      "restaurantId": "C023",
      "restaurantName": "레빗테이블",
      "name": "고르곤졸라피자",
      "category": "양식",
      "price": 12000,
      "spicy": 0,
      "salty": 2,
      "sweet": 4,
      "portion": 2,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "든든함",
        "데이트",
        "스트레스"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M076",
      "restaurantId": "C024",
      "restaurantName": "고가밀면",
      "name": "물밀면",
      "category": "분식",
      "price": 8000,
      "spicy": 0,
      "salty": 2,
      "sweet": 1,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "빠른식사",
        "해장",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M077",
      "restaurantId": "C024",
      "restaurantName": "고가밀면",
      "name": "비빔면",
      "category": "분식",
      "price": 8000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "빠른식사",
        "해장",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M078",
      "restaurantId": "C024",
      "restaurantName": "고가밀면",
      "name": "고가손만두",
      "category": "분식",
      "price": 8000,
      "spicy": 0,
      "salty": 2,
      "sweet": 2,
      "portion": 3,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "빠른식사",
        "해장",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M079",
      "restaurantId": "C025",
      "restaurantName": "가야밀면",
      "name": "물밀면",
      "category": "분식",
      "price": 8000,
      "spicy": 0,
      "salty": 2,
      "sweet": 2,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "빠른식사",
        "해장",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M080",
      "restaurantId": "C025",
      "restaurantName": "가야밀면",
      "name": "비빔밀면",
      "category": "분식",
      "price": 8000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 1,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "빠른식사",
        "해장",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M081",
      "restaurantId": "C025",
      "restaurantName": "가야밀면",
      "name": "돈까스",
      "category": "분식",
      "price": 8000,
      "spicy": 0,
      "salty": 2,
      "sweet": 1,
      "portion": 5,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "가볍게",
        "빠른식사",
        "해장",
        "단체"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M082",
      "restaurantId": "C026",
      "restaurantName": "유가네닭갈비",
      "name": "유가네닭갈비",
      "category": "한식",
      "price": 10500,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "데이트",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M083",
      "restaurantId": "C026",
      "restaurantName": "유가네닭갈비",
      "name": "콘치즈닭갈비",
      "category": "한식",
      "price": 12000,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "데이트",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M084",
      "restaurantId": "C026",
      "restaurantName": "유가네닭갈비",
      "name": "닭갈비철판볶음밥",
      "category": "한식",
      "price": 8000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "데이트",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M085",
      "restaurantId": "C026",
      "restaurantName": "유가네닭갈비",
      "name": "닭야채철판볶음밥",
      "category": "한식",
      "price": 8000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "데이트",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M086",
      "restaurantId": "C026",
      "restaurantName": "유가네닭갈비",
      "name": "미소허니닭갈비",
      "category": "한식",
      "price": 11500,
      "spicy": 2,
      "salty": 3,
      "sweet": 3,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "데이트",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M087",
      "restaurantId": "C026",
      "restaurantName": "유가네닭갈비",
      "name": "치즈철판볶음밥",
      "category": "한식",
      "price": 8500,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 4,
      "value": 3,
      "speed": 2,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "데이트",
        "포장",
        "배달",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M088",
      "restaurantId": "C027",
      "restaurantName": "호호돼지국밥",
      "name": "짜글이",
      "category": "한식",
      "price": 7000,
      "spicy": 1,
      "salty": 3,
      "sweet": 0,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M089",
      "restaurantId": "C027",
      "restaurantName": "호호돼지국밥",
      "name": "돼지국밥",
      "category": "한식",
      "price": 7000,
      "spicy": 0,
      "salty": 3,
      "sweet": 0,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M090",
      "restaurantId": "C027",
      "restaurantName": "호호돼지국밥",
      "name": "순대국밥",
      "category": "한식",
      "price": 7000,
      "spicy": 0,
      "salty": 3,
      "sweet": 0,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M091",
      "restaurantId": "C027",
      "restaurantName": "호호돼지국밥",
      "name": "내장국밥",
      "category": "한식",
      "price": 7000,
      "spicy": 0,
      "salty": 3,
      "sweet": 0,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M092",
      "restaurantId": "C027",
      "restaurantName": "호호돼지국밥",
      "name": "섞어국밥",
      "category": "한식",
      "price": 7000,
      "spicy": 0,
      "salty": 3,
      "sweet": 0,
      "portion": 4,
      "value": 5,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M093",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "짜장면",
      "category": "중식",
      "price": 5000,
      "spicy": 0,
      "salty": 4,
      "sweet": 3,
      "portion": 1,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M094",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "짬뽕",
      "category": "중식",
      "price": 8000,
      "spicy": 4,
      "salty": 3,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M095",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "볶음밥",
      "category": "중식",
      "price": 8000,
      "spicy": 0,
      "salty": 3,
      "sweet": 3,
      "portion": 1,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M096",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "간짜장",
      "category": "중식",
      "price": 8000,
      "spicy": 0,
      "salty": 4,
      "sweet": 3,
      "portion": 1,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M097",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "볶음짬뽕",
      "category": "중식",
      "price": 8000,
      "spicy": 3,
      "salty": 3,
      "sweet": 2,
      "portion": 2,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M098",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "미니탕수육",
      "category": "중식",
      "price": 10000,
      "spicy": 0,
      "salty": 2,
      "sweet": 1,
      "portion": 5,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M099",
      "restaurantId": "C028",
      "restaurantName": "장독짜장",
      "name": "쟁반짜장",
      "category": "중식",
      "price": 9000,
      "spicy": 2,
      "salty": 4,
      "sweet": 3,
      "portion": 2,
      "value": 4,
      "speed": 4,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "가볍게",
        "든든함",
        "가성비",
        "시험기간",
        "빠른식사",
        "데이트",
        "포장",
        "배달"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    },
    {
      "id": "M100",
      "restaurantId": "C029",
      "restaurantName": "돌솥밥수",
      "name": "돌솥밥 정식",
      "category": "한식",
      "price": 10000,
      "spicy": 2,
      "salty": 3,
      "sweet": 2,
      "portion": 3,
      "value": 3,
      "speed": 3,
      "signature": true,
      "available": true,
      "tags": [
        "혼밥",
        "단체",
        "든든함",
        "데이트",
        "시험기간"
      ],
      "source": "메뉴판 사진",
      "lastChecked": "2026-06-17T00:00:00",
      "recommendNote": ""
    }
  ],
  "meta": {
    "restaurantCount": 29,
    "menuCount": 100,
    "generatedFrom": "창원대_앞_음식점_메뉴_데이터수집_정리본.xlsx"
  }
};
