-- APPROVAL B PREVIEW ONLY. DO NOT EXECUTE WITHOUT SEPARATE EXPLICIT APPROVAL.
-- STATUS: NOT EXECUTED.
-- Intended for Supabase SQL Editor, psql, or equivalent direct PostgreSQL execution.
-- C001 is asserted and referenced, but never inserted, updated, upserted, or deleted.

begin;
set transaction isolation level serializable;
set local timezone = 'UTC';

lock table public.restaurants in share row exclusive mode;
lock table public.menus in share row exclusive mode;

do $catalog_migration$
declare
  v_actual integer;
  v_written integer;
  v_c001 jsonb;
  v_food_character_attnum smallint;
  v_food_character_data_type text;
  v_food_character_nullable text;
  v_food_character_default text;
  v_constraint_count integer;
  v_constraint_type text;
  v_constraint_validated boolean;
  v_constraint_no_inherit boolean;
  v_constraint_keys smallint[];
  v_constraint_expr text;
  v_constraint_literals text[];
  v_constraint_shape text;
  v_valid_semantics_ok boolean;
  v_invalid_semantics_ok boolean;
  v_expected_c001 constant jsonb := $c001_expected${
  "id": "C001",
  "name": "리코리코",
  "area": "정문",
  "address": "경상남도 창원시 의창구 퇴촌로25번길 6-32",
  "lat": 35.2425,
  "lng": 128.6898,
  "phone": "055-267-4300",
  "open_time": "10:00:00",
  "close_time": "20:40:00",
  "break_time": "",
  "closed_days": "일요일",
  "takeout": true,
  "delivery": true,
  "alone": true,
  "group_available": true,
  "seats": 54,
  "review_count": 173,
  "source": "네이버지도",
  "last_checked": "2026-06-15T00:00:00+00:00",
  "memo": "",
  "active": true
}$c001_expected$::jsonb;
  v_restaurants constant jsonb := $restaurants_payload$[
  {
    "id": "C002",
    "name": "달인의찜닭",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 43",
    "lat": 35.2423,
    "lng": 128.6898,
    "phone": "055-285-3070",
    "open_time": "10:30:00",
    "close_time": "21:00:00",
    "break_time": "",
    "closed_days": "일요일",
    "takeout": false,
    "delivery": false,
    "alone": false,
    "group_available": true,
    "seats": 70,
    "review_count": 146,
    "source": "네이버지도",
    "last_checked": "2026-06-16T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C003",
    "name": "엄마손",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 39",
    "lat": 35.2422,
    "lng": 128.6895,
    "phone": "X",
    "open_time": "X",
    "close_time": "X",
    "break_time": "X",
    "closed_days": "X",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 35,
    "review_count": 176,
    "source": "네이버지도",
    "last_checked": "2026-06-16T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C004",
    "name": "한솥도시락",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 37",
    "lat": 35.2421,
    "lng": 128.6893,
    "phone": "055-980-5519",
    "open_time": "08:15:00",
    "close_time": "20:30:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 15,
    "review_count": 561,
    "source": "네이버지도",
    "last_checked": "2026-06-16T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C005",
    "name": "경대컵밥",
    "area": "정문",
    "address": "경남 창원시 의창구 사림동 53-6",
    "lat": 35.2422,
    "lng": 128.689,
    "phone": "055-275-3353",
    "open_time": "10:00:00",
    "close_time": "19:30:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 25,
    "review_count": 37,
    "source": "기타",
    "last_checked": "2026-06-16T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C006",
    "name": "쇼부라멘",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 6-20 1층",
    "lat": 35.2422,
    "lng": 128.689,
    "phone": "055-267-0604",
    "open_time": "09:00:00",
    "close_time": "16:00:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 12,
    "review_count": 6,
    "source": "카카오맵",
    "last_checked": "2026-06-16T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C007",
    "name": "봉구스 밥버거",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 37",
    "lat": 35.2421,
    "lng": 128.6893,
    "phone": "055-281-9631",
    "open_time": "10:20:00",
    "close_time": "20:00:00",
    "break_time": "X",
    "closed_days": "일요일",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 8,
    "review_count": 94,
    "source": "네이버지도",
    "last_checked": "2026-06-17T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C008",
    "name": "미스사이공",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 6-24 1층",
    "lat": 35.2423,
    "lng": 128.6893,
    "phone": "055-262-5590",
    "open_time": "09:00:00",
    "close_time": "19:00:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 516,
    "source": "네이버지도",
    "last_checked": "2026-06-18T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C009",
    "name": "맘스터치",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 6-21",
    "lat": 35.2425,
    "lng": 128.6891,
    "phone": "055-286-3231",
    "open_time": "X",
    "close_time": "X",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 30,
    "review_count": 524,
    "source": "네이버지도",
    "last_checked": "2026-06-19T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C010",
    "name": "따뜻한밥상",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 6-15 따뜻한밥상",
    "lat": 35.2425,
    "lng": 128.6888,
    "phone": "X",
    "open_time": "10:30:00",
    "close_time": "20:00:00",
    "break_time": "14:30-17:00",
    "closed_days": "토요일,일요일",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 30,
    "review_count": 107,
    "source": "네이버지도",
    "last_checked": "2026-06-20T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C011",
    "name": "소소소국수집",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 6-5",
    "lat": 35.2422,
    "lng": 128.6883,
    "phone": "055-261-5233",
    "open_time": "X",
    "close_time": "X",
    "break_time": "X",
    "closed_days": "X",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 40,
    "review_count": 65,
    "source": "네이버지도",
    "last_checked": "2026-06-21T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C012",
    "name": "김밥천국",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 2",
    "lat": 35.2422,
    "lng": 128.6883,
    "phone": "055-274-2588",
    "open_time": "08:00:00",
    "close_time": "22:00:00",
    "break_time": "15:00-17:00",
    "closed_days": "X",
    "takeout": true,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 110,
    "source": "네이버지도",
    "last_checked": "2026-06-22T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C013",
    "name": "쌈마이 닭쌈밥",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로9번길 6-20 101호",
    "lat": 35.2419,
    "lng": 128.6876,
    "phone": "0507-1316-9003",
    "open_time": "10:00:00",
    "close_time": "20:00:00",
    "break_time": "X",
    "closed_days": "일요일",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 244,
    "source": "네이버지도",
    "last_checked": "2026-06-23T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C014",
    "name": "창대 비빔밥 뷔페",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 19 지하",
    "lat": 35.2418,
    "lng": 128.6875,
    "phone": "0507-1327-9883",
    "open_time": "11:00:00",
    "close_time": "14:00:00",
    "break_time": "X",
    "closed_days": "토요일,일요일",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 40,
    "review_count": 85,
    "source": "네이버지도",
    "last_checked": "2026-06-24T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C015",
    "name": "알촌",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 27 1층",
    "lat": 35.2418,
    "lng": 128.6883,
    "phone": "055-282-6363",
    "open_time": "09:40:00",
    "close_time": "20:30:00",
    "break_time": "X",
    "closed_days": "토요일",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 427,
    "source": "네이버지도",
    "last_checked": "2026-06-25T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C016",
    "name": "롯데리아",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 31-1",
    "lat": 35.242,
    "lng": 128.6887,
    "phone": "X",
    "open_time": "10:00:00",
    "close_time": "20:00:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 35,
    "review_count": 1200,
    "source": "네이버지도",
    "last_checked": "2026-06-26T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C017",
    "name": "이삭토스트",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로 327",
    "lat": 35.2416,
    "lng": 128.6907,
    "phone": "055-261-1676",
    "open_time": "11:00:00",
    "close_time": "21:10:00",
    "break_time": "X",
    "closed_days": "일요일",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 10,
    "review_count": 310,
    "source": "네이버지도",
    "last_checked": "2026-06-27T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C018",
    "name": "뼈따구",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로 327",
    "lat": 35.2416,
    "lng": 128.6907,
    "phone": "X",
    "open_time": "10:00:00",
    "close_time": "21:00:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 50,
    "review_count": 0,
    "source": "지인 제보",
    "last_checked": "2026-06-28T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C019",
    "name": "밀밭이야기",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로 323",
    "lat": 35.2414,
    "lng": 128.6908,
    "phone": "055-267-5670",
    "open_time": "X",
    "close_time": "X",
    "break_time": "X",
    "closed_days": "X",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 30,
    "review_count": 0,
    "source": "지인 제보",
    "last_checked": "2026-06-29T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C020",
    "name": "김밥일번지",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로 319-2 지하1층",
    "lat": 35.2412,
    "lng": 128.6907,
    "phone": "055-263-7772",
    "open_time": "09:00:00",
    "close_time": "20:00:00",
    "break_time": "X",
    "closed_days": "일요일",
    "takeout": true,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 50,
    "review_count": 874,
    "source": "네이버지도",
    "last_checked": "2026-06-30T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C021",
    "name": "팔팔마라탕",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로 41 1층",
    "lat": 35.2422,
    "lng": 128.6897,
    "phone": "055-261-6680",
    "open_time": "10:50:00",
    "close_time": "21:30:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 299,
    "source": "네이버지도",
    "last_checked": "2026-07-01T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C022",
    "name": "차곡히",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 7 1층",
    "lat": 35.2424,
    "lng": 128.6878,
    "phone": "0507-1345-5163",
    "open_time": "11:00:00",
    "close_time": "21:00:00",
    "break_time": "X",
    "closed_days": "토요일,일요일",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 284,
    "source": "네이버지도",
    "last_checked": "2026-07-02T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C023",
    "name": "레빗테이블",
    "area": "정문",
    "address": "경남 창원시 의창구 퇴촌로25번길 7 1층 래빗테이블",
    "lat": 35.2424,
    "lng": 128.6877,
    "phone": "0507-1308-0531",
    "open_time": "11:00:00",
    "close_time": "21:00:00",
    "break_time": "X",
    "closed_days": "토요일",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 25,
    "review_count": 168,
    "source": "네이버지도",
    "last_checked": "2026-07-03T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C024",
    "name": "고가밀면",
    "area": "정문",
    "address": "경남 창원시 의창구 사림로137번길 1",
    "lat": 35.2431,
    "lng": 128.6857,
    "phone": "X",
    "open_time": "10:50:00",
    "close_time": "15:30:00",
    "break_time": "X",
    "closed_days": "2,4번째 일요일",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 40,
    "review_count": 240,
    "source": "네이버지도",
    "last_checked": "2026-07-04T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C025",
    "name": "가야밀면",
    "area": "정문",
    "address": "경남 창원시 의창구 창이대로483번길 29-24",
    "lat": 35.2412,
    "lng": 128.6887,
    "phone": "055-262-2008",
    "open_time": "11:00:00",
    "close_time": "19:00:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 20,
    "review_count": 18,
    "source": "네이버지도",
    "last_checked": "2026-07-05T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C026",
    "name": "유가네 닭갈비",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로293번길 28 우영프라자 1층 115호",
    "lat": 35.2409,
    "lng": 128.6881,
    "phone": "055-273-8250",
    "open_time": "11:00:00",
    "close_time": "22:00:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 40,
    "review_count": 610,
    "source": "네이버지도",
    "last_checked": "2026-07-06T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C027",
    "name": "호호돼지국밥",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로 281",
    "lat": 35.2383,
    "lng": 128.6891,
    "phone": "055-263-3889",
    "open_time": "10:30:00",
    "close_time": "21:00:00",
    "break_time": "15:00-16:00",
    "closed_days": "일요일",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 60,
    "review_count": 603,
    "source": "네이버지도",
    "last_checked": "2026-07-07T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C028",
    "name": "장독짜장",
    "area": "정문",
    "address": "경남 창원시 의창구 창이대로469번길 19",
    "lat": 35.2404,
    "lng": 128.6878,
    "phone": "055-288-1536",
    "open_time": "10:30:00",
    "close_time": "20:20:00",
    "break_time": "X",
    "closed_days": "X",
    "takeout": true,
    "delivery": true,
    "alone": true,
    "group_available": true,
    "seats": 80,
    "review_count": 503,
    "source": "네이버지도",
    "last_checked": "2026-07-08T00:00:00",
    "memo": "",
    "active": true
  },
  {
    "id": "C029",
    "name": "돌솥밥수",
    "area": "정문",
    "address": "경남 창원시 의창구 용지로293번길 21 반지하층 돌솥밥수",
    "lat": 35.2403,
    "lng": 128.688,
    "phone": "055-261-2905",
    "open_time": "11:00:00",
    "close_time": "20:30:00",
    "break_time": "15:00-17:00",
    "closed_days": "X",
    "takeout": false,
    "delivery": false,
    "alone": true,
    "group_available": true,
    "seats": 80,
    "review_count": 293,
    "source": "네이버지도",
    "last_checked": "2026-07-09T00:00:00",
    "memo": "",
    "active": true
  }
]$restaurants_payload$::jsonb;
  v_menus constant jsonb := $menus_payload$[
  {
    "id": "M001",
    "restaurant_id": "C001",
    "restaurant_name": "리코리코",
    "name": "닭고기 부리또",
    "category": "햄버거",
    "price": 5000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "빠른식사",
      "든든함",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M002",
    "restaurant_id": "C001",
    "restaurant_name": "리코리코",
    "name": "소고기 부리또",
    "category": "햄버거",
    "price": 5800,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "빠른식사",
      "든든함",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M003",
    "restaurant_id": "C001",
    "restaurant_name": "리코리코",
    "name": "섞어 부리또",
    "category": "햄버거",
    "price": 5000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "빠른식사",
      "든든함",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M004",
    "restaurant_id": "C001",
    "restaurant_name": "리코리코",
    "name": "치킨텐더 부리또",
    "category": "햄버거",
    "price": 6500,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "빠른식사",
      "든든함",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M005",
    "restaurant_id": "C001",
    "restaurant_name": "리코리코",
    "name": "제육 부리또",
    "category": "햄버거",
    "price": 6000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "빠른식사",
      "든든함",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M006",
    "restaurant_id": "C002",
    "restaurant_name": "달인의찜닭",
    "name": "달인 순살 찜닭",
    "category": "찜/탕",
    "price": 23000,
    "spicy": 3,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "단체",
      "데이트",
      "든든함",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M007",
    "restaurant_id": "C002",
    "restaurant_name": "달인의찜닭",
    "name": "달인 치즈순살 찜닭",
    "category": "찜/탕",
    "price": 26000,
    "spicy": 3,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "단체",
      "데이트",
      "든든함",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M008",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "두루치기",
    "category": "한식",
    "price": 11000,
    "spicy": 2,
    "salty": 2,
    "sweet": 4,
    "portion": 3,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M009",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "된장찌개",
    "category": "한식",
    "price": 6000,
    "spicy": 1,
    "salty": 3,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M010",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "김치찌개",
    "category": "한식",
    "price": 6000,
    "spicy": 1,
    "salty": 3,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M011",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "순두부찌개",
    "category": "한식",
    "price": 6500,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M012",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "뚝배기불고기",
    "category": "한식",
    "price": 8000,
    "spicy": 0,
    "salty": 2,
    "sweet": 4,
    "portion": 4,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M013",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "돌솥비빔밥",
    "category": "한식",
    "price": 6500,
    "spicy": 0,
    "salty": 2,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M014",
    "restaurant_id": "C003",
    "restaurant_name": "엄마손",
    "name": "육개장",
    "category": "한식",
    "price": 7000,
    "spicy": 3,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "해장"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M015",
    "restaurant_id": "C004",
    "restaurant_name": "한솥도시락",
    "name": "빅치킨마요",
    "category": "도시락",
    "price": 4600,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M016",
    "restaurant_id": "C004",
    "restaurant_name": "한솥도시락",
    "name": "제육 많이 덮밥",
    "category": "도시락",
    "price": 6500,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M017",
    "restaurant_id": "C004",
    "restaurant_name": "한솥도시락",
    "name": "돈까스 도련님 고기고기",
    "category": "도시락",
    "price": 7300,
    "spicy": 0,
    "salty": 2,
    "sweet": 2,
    "portion": 5,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M018",
    "restaurant_id": "C004",
    "restaurant_name": "한솥도시락",
    "name": "왕카레돈까스 덮밥",
    "category": "도시락",
    "price": 6700,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M019",
    "restaurant_id": "C005",
    "restaurant_name": "경대컵밥",
    "name": "경대컵밥도시락",
    "category": "도시락",
    "price": 6400,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M020",
    "restaurant_id": "C005",
    "restaurant_name": "경대컵밥",
    "name": "오리훈제컵밥도시락",
    "category": "도시락",
    "price": 7400,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M021",
    "restaurant_id": "C005",
    "restaurant_name": "경대컵밥",
    "name": "제육컵밥도시락",
    "category": "도시락",
    "price": 7400,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M022",
    "restaurant_id": "C005",
    "restaurant_name": "경대컵밥",
    "name": "치즈컵밥도시락",
    "category": "도시락",
    "price": 7400,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "가성비",
      "혼밥",
      "단체",
      "든든함",
      "가볍게",
      "포장",
      "배달",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M023",
    "restaurant_id": "C006",
    "restaurant_name": "쇼부라멘",
    "name": "소유라멘",
    "category": "일식/돈까스",
    "price": 5500,
    "spicy": 0,
    "salty": 4,
    "sweet": 4,
    "portion": 2,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "가볍게",
      "시험기간",
      "빠른식사",
      "해장",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M024",
    "restaurant_id": "C006",
    "restaurant_name": "쇼부라멘",
    "name": "미소라멘",
    "category": "일식/돈까스",
    "price": 6000,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 2,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "가볍게",
      "시험기간",
      "빠른식사",
      "해장",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M025",
    "restaurant_id": "C006",
    "restaurant_name": "쇼부라멘",
    "name": "돈코츠라멘",
    "category": "일식/돈까스",
    "price": 6500,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 2,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "가볍게",
      "시험기간",
      "빠른식사",
      "해장",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M026",
    "restaurant_id": "C006",
    "restaurant_name": "쇼부라멘",
    "name": "탄탄멘",
    "category": "일식/돈까스",
    "price": 7000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "가볍게",
      "시험기간",
      "빠른식사",
      "해장",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M027",
    "restaurant_id": "C007",
    "restaurant_name": "봉구스 밥버거",
    "name": "봉구스",
    "category": "도시락",
    "price": 3500,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 1,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "포장",
      "배달",
      "가성비"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M028",
    "restaurant_id": "C007",
    "restaurant_name": "봉구스 밥버거",
    "name": "햄치즈",
    "category": "도시락",
    "price": 5100,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 2,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M029",
    "restaurant_id": "C007",
    "restaurant_name": "봉구스 밥버거",
    "name": "봉구킹",
    "category": "도시락",
    "price": 7300,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M030",
    "restaurant_id": "C007",
    "restaurant_name": "봉구스 밥버거",
    "name": "봉구퀸",
    "category": "도시락",
    "price": 7300,
    "spicy": 0,
    "salty": 3,
    "sweet": 4,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M031",
    "restaurant_id": "C008",
    "restaurant_name": "미스사이공",
    "name": "소고기 쌀국수",
    "category": "아시안",
    "price": 6500,
    "spicy": 0,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M032",
    "restaurant_id": "C008",
    "restaurant_name": "미스사이공",
    "name": "닭고기 쌀국수",
    "category": "아시안",
    "price": 6500,
    "spicy": 0,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M033",
    "restaurant_id": "C008",
    "restaurant_name": "미스사이공",
    "name": "사이공 볶음밥",
    "category": "아시안",
    "price": 6500,
    "spicy": 0,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "데이트"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M034",
    "restaurant_id": "C009",
    "restaurant_name": "맘스터치",
    "name": "싸이버거 세트",
    "category": "햄버거",
    "price": 9000,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 5,
    "value": 2,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "포장",
      "배달",
      "단체",
      "든든함"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M035",
    "restaurant_id": "C009",
    "restaurant_name": "맘스터치",
    "name": "아라비아따치즈버거 세트",
    "category": "햄버거",
    "price": 11500,
    "spicy": 2,
    "salty": 3,
    "sweet": 4,
    "portion": 5,
    "value": 2,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "포장",
      "배달",
      "단체",
      "든든함"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M036",
    "restaurant_id": "C009",
    "restaurant_name": "맘스터치",
    "name": "화이트갈릭싸이버거 세트",
    "category": "햄버거",
    "price": 9600,
    "spicy": 1,
    "salty": 3,
    "sweet": 4,
    "portion": 5,
    "value": 2,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "포장",
      "배달",
      "단체",
      "든든함"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M037",
    "restaurant_id": "C010",
    "restaurant_name": "따뜻한밥상",
    "name": "김치찌개",
    "category": "한식",
    "price": 5000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "시험기간",
      "빠른식사",
      "든든함",
      "가성비",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M038",
    "restaurant_id": "C011",
    "restaurant_name": "소소소국수집",
    "name": "잔치국수",
    "category": "분식",
    "price": 6000,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "시험기간",
      "든든함",
      "빠른식사",
      "해장",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M039",
    "restaurant_id": "C011",
    "restaurant_name": "소소소국수집",
    "name": "비빔국수",
    "category": "분식",
    "price": 7000,
    "spicy": 2,
    "salty": 3,
    "sweet": 4,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "시험기간",
      "든든함",
      "빠른식사",
      "해장",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M040",
    "restaurant_id": "C011",
    "restaurant_name": "소소소국수집",
    "name": "열무국수",
    "category": "분식",
    "price": 7000,
    "spicy": 2,
    "salty": 3,
    "sweet": 4,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "시험기간",
      "든든함",
      "빠른식사",
      "해장",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M041",
    "restaurant_id": "C012",
    "restaurant_name": "김밥천국",
    "name": "참치마요김밥",
    "category": "분식",
    "price": 3500,
    "spicy": 0,
    "salty": 2,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 5,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "가성비",
      "포장"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M042",
    "restaurant_id": "C012",
    "restaurant_name": "김밥천국",
    "name": "순두부찌개",
    "category": "분식",
    "price": 5500,
    "spicy": 3,
    "salty": 3,
    "sweet": 2,
    "portion": 1,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "해장"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M043",
    "restaurant_id": "C012",
    "restaurant_name": "김밥천국",
    "name": "돈까스",
    "category": "분식",
    "price": 6000,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M044",
    "restaurant_id": "C013",
    "restaurant_name": "쌈마이 닭쌈밥",
    "name": "쌈마이 닭쌈밥 백반도시락",
    "category": "도시락",
    "price": 8900,
    "spicy": 0,
    "salty": 3,
    "sweet": 0,
    "portion": 5,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "시험기간",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M045",
    "restaurant_id": "C013",
    "restaurant_name": "쌈마이 닭쌈밥",
    "name": "양념닭쌈밥 백반도시락",
    "category": "도시락",
    "price": 9500,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 5,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "시험기간",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M046",
    "restaurant_id": "C014",
    "restaurant_name": "창대 비빔밥 뷔페",
    "name": "비빔밥",
    "category": "한식",
    "price": 8000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 3,
    "speed": 5,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M047",
    "restaurant_id": "C015",
    "restaurant_name": "알촌",
    "name": "순한알밥",
    "category": "한식",
    "price": 5300,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "포장",
      "배달",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M048",
    "restaurant_id": "C015",
    "restaurant_name": "알촌",
    "name": "약매알밥",
    "category": "한식",
    "price": 5500,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "포장",
      "배달",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M049",
    "restaurant_id": "C015",
    "restaurant_name": "알촌",
    "name": "매콤알밥",
    "category": "한식",
    "price": 5600,
    "spicy": 4,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "든든함",
      "빠른식사",
      "포장",
      "배달",
      "가볍게"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M050",
    "restaurant_id": "C016",
    "restaurant_name": "롯데리아",
    "name": "모짜렐라 인 더 버거 베이컨 세트",
    "category": "햄버거",
    "price": 11700,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 2,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "단체",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M051",
    "restaurant_id": "C016",
    "restaurant_name": "롯데리아",
    "name": "불고기버거",
    "category": "햄버거",
    "price": 8900,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 2,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "단체",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M052",
    "restaurant_id": "C016",
    "restaurant_name": "롯데리아",
    "name": "핫크리스피치킨버거 세트",
    "category": "햄버거",
    "price": 10000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 2,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "단체",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M053",
    "restaurant_id": "C017",
    "restaurant_name": "이삭토스트",
    "name": "햄스페셜 토스트",
    "category": "햄버거",
    "price": 5100,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "단체",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M054",
    "restaurant_id": "C017",
    "restaurant_name": "이삭토스트",
    "name": "햄치즈 토스트",
    "category": "햄버거",
    "price": 4500,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "단체",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M055",
    "restaurant_id": "C017",
    "restaurant_name": "이삭토스트",
    "name": "베이컨 포테이토 피자",
    "category": "햄버거",
    "price": 6500,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 3,
    "value": 3,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "시험기간",
      "단체",
      "빠른식사",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M056",
    "restaurant_id": "C018",
    "restaurant_name": "뼈따구",
    "name": "뼈해장국",
    "category": "찜/탕",
    "price": 10000,
    "spicy": 1,
    "salty": 3,
    "sweet": 2,
    "portion": 4,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "시험기간",
      "포장",
      "해장",
      "비오는날",
      "든든함"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M057",
    "restaurant_id": "C018",
    "restaurant_name": "뼈따구",
    "name": "콩나물해장국",
    "category": "찜/탕",
    "price": 10000,
    "spicy": 1,
    "salty": 3,
    "sweet": 2,
    "portion": 2,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "시험기간",
      "포장",
      "해장",
      "비오는날",
      "든든함"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M058",
    "restaurant_id": "C019",
    "restaurant_name": "밀밭이야기",
    "name": "촌국수",
    "category": "한식",
    "price": 6000,
    "spicy": 1,
    "salty": 3,
    "sweet": 1,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M059",
    "restaurant_id": "C019",
    "restaurant_name": "밀밭이야기",
    "name": "비빔국수",
    "category": "한식",
    "price": 7000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M060",
    "restaurant_id": "C019",
    "restaurant_name": "밀밭이야기",
    "name": "양푼비빔밥",
    "category": "한식",
    "price": 8000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M061",
    "restaurant_id": "C019",
    "restaurant_name": "밀밭이야기",
    "name": "해물전",
    "category": "한식",
    "price": 7000,
    "spicy": 1,
    "salty": 2,
    "sweet": 0,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M062",
    "restaurant_id": "C019",
    "restaurant_name": "밀밭이야기",
    "name": "수제비",
    "category": "한식",
    "price": 7000,
    "spicy": 0,
    "salty": 3,
    "sweet": 1,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M063",
    "restaurant_id": "C019",
    "restaurant_name": "밀밭이야기",
    "name": "들깨칼국수",
    "category": "한식",
    "price": 9000,
    "spicy": 0,
    "salty": 3,
    "sweet": 2,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M064",
    "restaurant_id": "C020",
    "restaurant_name": "김밥일번지",
    "name": "일번지김밥",
    "category": "분식",
    "price": 4000,
    "spicy": 0,
    "salty": 2,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날",
      "포장",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M065",
    "restaurant_id": "C020",
    "restaurant_name": "김밥일번지",
    "name": "콩나물비빔밥",
    "category": "분식",
    "price": 7000,
    "spicy": 1,
    "salty": 2,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날",
      "포장",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M066",
    "restaurant_id": "C020",
    "restaurant_name": "김밥일번지",
    "name": "일번지라면",
    "category": "분식",
    "price": 4500,
    "spicy": 2,
    "salty": 3,
    "sweet": 1,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날",
      "포장",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M067",
    "restaurant_id": "C020",
    "restaurant_name": "김밥일번지",
    "name": "엄마떡볶이",
    "category": "분식",
    "price": 7000,
    "spicy": 3,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "비오는날",
      "포장",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M068",
    "restaurant_id": "C021",
    "restaurant_name": "팔팔마라탕",
    "name": "88마라탕",
    "category": "찜/탕",
    "price": 9800,
    "spicy": 5,
    "salty": 3,
    "sweet": 1,
    "portion": 3,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "포장",
      "배달",
      "스트레스"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M069",
    "restaurant_id": "C022",
    "restaurant_name": "차곡히",
    "name": "순두부 제육볶음세트",
    "category": "한식",
    "price": 12000,
    "spicy": 3,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 2,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "단체",
      "데이트",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M070",
    "restaurant_id": "C022",
    "restaurant_name": "차곡히",
    "name": "된장찌개 제육볶음 세트",
    "category": "한식",
    "price": 12000,
    "spicy": 3,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 2,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "든든함",
      "단체",
      "데이트",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M071",
    "restaurant_id": "C023",
    "restaurant_name": "레빗테이블",
    "name": "수제등심 돈가스",
    "category": "양식",
    "price": 10000,
    "spicy": 0,
    "salty": 2,
    "sweet": 1,
    "portion": 5,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "든든함",
      "데이트",
      "스트레스"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M072",
    "restaurant_id": "C023",
    "restaurant_name": "레빗테이블",
    "name": "레빗크림 파스타",
    "category": "양식",
    "price": 9500,
    "spicy": 1,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "든든함",
      "데이트",
      "스트레스"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M073",
    "restaurant_id": "C023",
    "restaurant_name": "레빗테이블",
    "name": "레빗로제 파스타",
    "category": "양식",
    "price": 11000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "든든함",
      "데이트",
      "스트레스"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M074",
    "restaurant_id": "C023",
    "restaurant_name": "레빗테이블",
    "name": "베이컨 크림 리조또",
    "category": "양식",
    "price": 11000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 2,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "든든함",
      "데이트",
      "스트레스"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M075",
    "restaurant_id": "C023",
    "restaurant_name": "레빗테이블",
    "name": "고르곤졸라피자",
    "category": "양식",
    "price": 12000,
    "spicy": 0,
    "salty": 2,
    "sweet": 4,
    "portion": 2,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "든든함",
      "데이트",
      "스트레스"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M076",
    "restaurant_id": "C024",
    "restaurant_name": "고가밀면",
    "name": "물밀면",
    "category": "분식",
    "price": 8000,
    "spicy": 0,
    "salty": 2,
    "sweet": 1,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "빠른식사",
      "해장",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M077",
    "restaurant_id": "C024",
    "restaurant_name": "고가밀면",
    "name": "비빔면",
    "category": "분식",
    "price": 8000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "빠른식사",
      "해장",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M078",
    "restaurant_id": "C024",
    "restaurant_name": "고가밀면",
    "name": "고가손만두",
    "category": "분식",
    "price": 8000,
    "spicy": 0,
    "salty": 2,
    "sweet": 2,
    "portion": 3,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "빠른식사",
      "해장",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "quick-snack"
  },
  {
    "id": "M079",
    "restaurant_id": "C025",
    "restaurant_name": "가야밀면",
    "name": "물밀면",
    "category": "분식",
    "price": 8000,
    "spicy": 0,
    "salty": 2,
    "sweet": 2,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "빠른식사",
      "해장",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M080",
    "restaurant_id": "C025",
    "restaurant_name": "가야밀면",
    "name": "비빔밀면",
    "category": "분식",
    "price": 8000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 1,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "빠른식사",
      "해장",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M081",
    "restaurant_id": "C025",
    "restaurant_name": "가야밀면",
    "name": "돈까스",
    "category": "분식",
    "price": 8000,
    "spicy": 0,
    "salty": 2,
    "sweet": 1,
    "portion": 5,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "가볍게",
      "빠른식사",
      "해장",
      "단체"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M082",
    "restaurant_id": "C026",
    "restaurant_name": "유가네 닭갈비",
    "name": "유가네닭갈비",
    "category": "한식",
    "price": 10500,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "데이트",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M083",
    "restaurant_id": "C026",
    "restaurant_name": "유가네 닭갈비",
    "name": "콘치즈닭갈비",
    "category": "한식",
    "price": 12000,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "데이트",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M084",
    "restaurant_id": "C026",
    "restaurant_name": "유가네 닭갈비",
    "name": "닭갈비철판볶음밥",
    "category": "한식",
    "price": 8000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "데이트",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M085",
    "restaurant_id": "C026",
    "restaurant_name": "유가네 닭갈비",
    "name": "닭야채철판볶음밥",
    "category": "한식",
    "price": 8000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "데이트",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M086",
    "restaurant_id": "C026",
    "restaurant_name": "유가네 닭갈비",
    "name": "미소허니닭갈비",
    "category": "한식",
    "price": 11500,
    "spicy": 2,
    "salty": 3,
    "sweet": 3,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "데이트",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M087",
    "restaurant_id": "C026",
    "restaurant_name": "유가네 닭갈비",
    "name": "치즈철판볶음밥",
    "category": "한식",
    "price": 8500,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 4,
    "value": 3,
    "speed": 2,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "데이트",
      "포장",
      "배달",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M088",
    "restaurant_id": "C027",
    "restaurant_name": "호호돼지국밥",
    "name": "짜글이",
    "category": "한식",
    "price": 7000,
    "spicy": 1,
    "salty": 3,
    "sweet": 0,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M089",
    "restaurant_id": "C027",
    "restaurant_name": "호호돼지국밥",
    "name": "돼지국밥",
    "category": "한식",
    "price": 7000,
    "spicy": 0,
    "salty": 3,
    "sweet": 0,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M090",
    "restaurant_id": "C027",
    "restaurant_name": "호호돼지국밥",
    "name": "순대국밥",
    "category": "한식",
    "price": 7000,
    "spicy": 0,
    "salty": 3,
    "sweet": 0,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M091",
    "restaurant_id": "C027",
    "restaurant_name": "호호돼지국밥",
    "name": "내장국밥",
    "category": "한식",
    "price": 7000,
    "spicy": 0,
    "salty": 3,
    "sweet": 0,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M092",
    "restaurant_id": "C027",
    "restaurant_name": "호호돼지국밥",
    "name": "섞어국밥",
    "category": "한식",
    "price": 7000,
    "spicy": 0,
    "salty": 3,
    "sweet": 0,
    "portion": 4,
    "value": 5,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "hot-soup"
  },
  {
    "id": "M093",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "짜장면",
    "category": "중식",
    "price": 5000,
    "spicy": 0,
    "salty": 4,
    "sweet": 3,
    "portion": 1,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M094",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "짬뽕",
    "category": "중식",
    "price": 8000,
    "spicy": 4,
    "salty": 3,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M095",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "볶음밥",
    "category": "중식",
    "price": 8000,
    "spicy": 0,
    "salty": 3,
    "sweet": 3,
    "portion": 1,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  },
  {
    "id": "M096",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "간짜장",
    "category": "중식",
    "price": 8000,
    "spicy": 0,
    "salty": 4,
    "sweet": 3,
    "portion": 1,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M097",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "볶음짬뽕",
    "category": "중식",
    "price": 8000,
    "spicy": 3,
    "salty": 3,
    "sweet": 2,
    "portion": 2,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M098",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "미니탕수육",
    "category": "중식",
    "price": 10000,
    "spicy": 0,
    "salty": 2,
    "sweet": 1,
    "portion": 5,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "main-dish"
  },
  {
    "id": "M099",
    "restaurant_id": "C028",
    "restaurant_name": "장독짜장",
    "name": "쟁반짜장",
    "category": "중식",
    "price": 9000,
    "spicy": 2,
    "salty": 4,
    "sweet": 3,
    "portion": 2,
    "value": 4,
    "speed": 4,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "가볍게",
      "든든함",
      "가성비",
      "시험기간",
      "빠른식사",
      "데이트",
      "포장",
      "배달"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "noodle-special"
  },
  {
    "id": "M100",
    "restaurant_id": "C029",
    "restaurant_name": "돌솥밥수",
    "name": "돌솥밥 정식",
    "category": "한식",
    "price": 10000,
    "spicy": 2,
    "salty": 3,
    "sweet": 2,
    "portion": 3,
    "value": 3,
    "speed": 3,
    "signature": true,
    "available": true,
    "tags": [
      "혼밥",
      "단체",
      "든든함",
      "데이트",
      "시험기간"
    ],
    "source": "메뉴판 사진",
    "last_checked": "2026-06-17T00:00:00",
    "recommend_note": "",
    "food_character": "rice-meal"
  }
]$menus_payload$::jsonb;
begin
  -- Fail closed unless the manually applied Approval A schema contract is exact.
  select data_type, is_nullable, column_default
    into v_food_character_data_type, v_food_character_nullable, v_food_character_default
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'menus'
    and column_name = 'food_character';

  if not found then
    raise exception 'Approval B schema baseline failed: public.menus.food_character is missing';
  end if;
  if v_food_character_data_type is distinct from 'text'
     or v_food_character_nullable is distinct from 'YES'
     or v_food_character_default is not null then
    raise exception
      'Approval B schema baseline failed: food_character definition mismatch (type=%, nullable=%, default=%)',
      v_food_character_data_type,
      v_food_character_nullable,
      coalesce(v_food_character_default, 'none');
  end if;

  select attnum
    into v_food_character_attnum
  from pg_attribute
  where attrelid = 'public.menus'::regclass
    and attname = 'food_character'
    and not attisdropped;

  if not found then
    raise exception 'Approval B schema baseline failed: food_character catalog metadata is missing';
  end if;

  select count(*)
    into v_constraint_count
  from pg_constraint
  where conrelid = 'public.menus'::regclass
    and conname = 'menus_food_character_allowed';

  if v_constraint_count <> 1 then
    raise exception
      'Approval B schema baseline failed: menus_food_character_allowed count is %, expected 1',
      v_constraint_count;
  end if;

  select contype::text,
         convalidated,
         connoinherit,
         conkey,
         pg_get_expr(conbin, conrelid, true)
    into v_constraint_type,
         v_constraint_validated,
         v_constraint_no_inherit,
         v_constraint_keys,
         v_constraint_expr
  from pg_constraint
  where conrelid = 'public.menus'::regclass
    and conname = 'menus_food_character_allowed';

  if v_constraint_type is distinct from 'c'
     or v_constraint_validated is not true
     or v_constraint_no_inherit is not false
     or v_constraint_keys is distinct from array[v_food_character_attnum]::smallint[] then
    raise exception
      'Approval B schema baseline failed: menus_food_character_allowed metadata mismatch';
  end if;

  select coalesce(array_agg(capture[1] order by capture[1]), array[]::text[])
    into v_constraint_literals
  from regexp_matches(v_constraint_expr, '''([^'']*)''', 'g') as matches(capture);

  if v_constraint_literals is distinct from array['hot-soup', 'main-dish', 'noodle-special', 'quick-snack', 'rice-meal']::text[] then
    raise exception
      'Approval B schema baseline failed: Food Character allowed-value set mismatch (%)',
      v_constraint_literals;
  end if;

  v_constraint_shape := lower(v_constraint_expr);
  v_constraint_shape := replace(v_constraint_shape, '::text[]', '');
  v_constraint_shape := replace(v_constraint_shape, '::text', '');
  v_constraint_shape := regexp_replace(v_constraint_shape, '''[^'']*''', '''value''', 'g');
  v_constraint_shape := regexp_replace(v_constraint_shape, '[[:space:]()]', '', 'g');

  if v_constraint_shape is distinct from 'food_characterisnullorfood_character=anyarray[''value'',''value'',''value'',''value'',''value'']' then
    raise exception
      'Approval B schema baseline failed: Food Character CHECK expression shape mismatch (%)',
      v_constraint_expr;
  end if;

  execute format(
    'select coalesce(bool_and((%s) is true), false) from (values (null::text), (''rice-meal''::text), (''noodle-special''::text), (''hot-soup''::text), (''quick-snack''::text), (''main-dish''::text)) as probe(food_character)',
    v_constraint_expr
  ) into v_valid_semantics_ok;

  execute format(
    'select coalesce(bool_and((%s) is false), false) from (values (''''::text), (''invalid''::text), (''secondary-trait''::text), (''rice_meal''::text)) as probe(food_character)',
    v_constraint_expr
  ) into v_invalid_semantics_ok;

  if v_valid_semantics_ok is not true or v_invalid_semantics_ok is not true then
    raise exception
      'Approval B schema baseline failed: Food Character CHECK semantic probes failed';
  end if;

  select count(*) into v_actual from public.restaurants;
  if v_actual <> 1 then
    raise exception 'Baseline assertion failed: restaurants count is %, expected 1', v_actual;
  end if;

  select count(*) into v_actual from public.menus;
  if v_actual <> 0 then
    raise exception 'Baseline assertion failed: menus count is %, expected 0', v_actual;
  end if;

  if not exists (select 1 from public.restaurants where id = 'C001' and name = '리코리코') then
    raise exception 'Baseline assertion failed: C001 리코리코 is missing';
  end if;

  select to_jsonb(snapshot) into v_c001
  from (
    select "id", "name", "area", "address", "lat", "lng", "phone", "open_time", "close_time", "break_time", "closed_days", "takeout", "delivery", "alone", "group_available", "seats", "review_count", "source", "last_checked", "memo", "active"
    from public.restaurants
    where id = 'C001'
  ) as snapshot;
  if v_c001 is null or v_c001 is distinct from v_expected_c001 then
    raise exception 'Baseline assertion failed: C001 fingerprint differs from the approved backup';
  end if;

  if exists (
    select 1 from public.restaurants
    where id = any (array(select 'C' || to_char(value, 'FM000') from generate_series(2, 29) as series(value)))
  ) then
    raise exception 'ID collision: at least one of C002-C029 already exists';
  end if;

  if exists (
    select 1 from public.menus
    where id = any (array(select 'M' || to_char(value, 'FM000') from generate_series(1, 100) as series(value)))
  ) then
    raise exception 'ID collision: at least one of M001-M100 already exists';
  end if;

  insert into public.restaurants ("id", "name", "area", "address", "lat", "lng", "phone", "open_time", "close_time", "break_time", "closed_days", "takeout", "delivery", "alone", "group_available", "seats", "review_count", "source", "last_checked", "memo", "active")
  select payload."id", payload."name", payload."area", payload."address", payload."lat", payload."lng", payload."phone", payload."open_time", payload."close_time", payload."break_time", payload."closed_days", payload."takeout", payload."delivery", payload."alone", payload."group_available", payload."seats", payload."review_count", payload."source", payload."last_checked", payload."memo", payload."active"
  from jsonb_populate_recordset(null::public.restaurants, v_restaurants) as payload;
  get diagnostics v_written = row_count;
  if v_written <> 28 then
    raise exception 'Restaurant insert assertion failed: wrote %, expected 28', v_written;
  end if;

  insert into public.menus ("id", "restaurant_id", "restaurant_name", "name", "category", "price", "spicy", "salty", "sweet", "portion", "value", "speed", "signature", "available", "tags", "source", "last_checked", "recommend_note", "food_character")
  select payload."id", payload."restaurant_id", payload."restaurant_name", payload."name", payload."category", payload."price", payload."spicy", payload."salty", payload."sweet", payload."portion", payload."value", payload."speed", payload."signature", payload."available", payload."tags", payload."source", payload."last_checked", payload."recommend_note", payload."food_character"
  from jsonb_populate_recordset(null::public.menus, v_menus) as payload;
  get diagnostics v_written = row_count;
  if v_written <> 100 then
    raise exception 'Menu insert assertion failed: wrote %, expected 100', v_written;
  end if;

  if (select count(*) from public.restaurants) <> 29 then
    raise exception 'Post-write assertion failed: restaurants total must be 29';
  end if;
  if (select count(*) from public.menus) <> 100 then
    raise exception 'Post-write assertion failed: menus total must be 100';
  end if;
  if (
    select count(*) from public.restaurants
    where id = any (array(select 'C' || to_char(value, 'FM000') from generate_series(2, 29) as series(value)))
  ) <> 28 then
    raise exception 'Post-write assertion failed: C002-C029 count must be 28';
  end if;
  if (
    select count(*) from public.menus
    where id = any (array(select 'M' || to_char(value, 'FM000') from generate_series(1, 100) as series(value)))
  ) <> 100 then
    raise exception 'Post-write assertion failed: M001-M100 count must be 100';
  end if;
  if exists (
    select 1 from public.menus
    where food_character is null
       or food_character not in ('rice-meal', 'noodle-special', 'hot-soup', 'quick-snack', 'main-dish')
  ) then
    raise exception 'Post-write assertion failed: null or invalid Food Character exists';
  end if;

  if (select count(*) from public.menus where food_character = 'rice-meal') <> 24 then
    raise exception 'Post-write assertion failed: rice-meal count must be 24';
  end if;

  if (select count(*) from public.menus where food_character = 'noodle-special') <> 25 then
    raise exception 'Post-write assertion failed: noodle-special count must be 25';
  end if;

  if (select count(*) from public.menus where food_character = 'hot-soup') <> 16 then
    raise exception 'Post-write assertion failed: hot-soup count must be 16';
  end if;

  if (select count(*) from public.menus where food_character = 'quick-snack') <> 21 then
    raise exception 'Post-write assertion failed: quick-snack count must be 21';
  end if;

  if (select count(*) from public.menus where food_character = 'main-dish') <> 14 then
    raise exception 'Post-write assertion failed: main-dish count must be 14';
  end if;

  if exists (
    select 1
    from public.menus as menu
    left join public.restaurants as restaurant on restaurant.id = menu.restaurant_id
    where restaurant.id is null
  ) then
    raise exception 'Post-write assertion failed: orphan menu exists';
  end if;
  if exists (
    select 1
    from public.menus as menu
    left join public.restaurants as restaurant on restaurant.id = menu.restaurant_id
    where menu.available is true and restaurant.id is null
  ) then
    raise exception 'Post-write assertion failed: sellable menu references a missing restaurant';
  end if;
  if exists (
    select 1
    from public.menus as menu
    join public.restaurants as restaurant on restaurant.id = menu.restaurant_id
    where menu.available is true and restaurant.active is false
  ) then
    raise exception 'Post-write assertion failed: sellable menu references an inactive restaurant';
  end if;

  select to_jsonb(snapshot) into v_c001
  from (
    select "id", "name", "area", "address", "lat", "lng", "phone", "open_time", "close_time", "break_time", "closed_days", "takeout", "delivery", "alone", "group_available", "seats", "review_count", "source", "last_checked", "memo", "active"
    from public.restaurants
    where id = 'C001'
  ) as snapshot;
  if v_c001 is distinct from v_expected_c001 then
    raise exception 'Post-write assertion failed: C001 changed';
  end if;
end
$catalog_migration$;

commit;

-- PostgreSQL MVCC keeps these inserts invisible to other sessions until COMMIT.
-- Any assertion error aborts the transaction, so the expected visible states are only 1/0 or 29/100.
